import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ResumeExportService {
  static Future<void> exportResume({
    required String name,
    required String email,
    required String major,
    required String activityStatus,
    String? company,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(40),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(name, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 8),
                pw.Text(email, style: const pw.TextStyle(fontSize: 12)),
                pw.Divider(thickness: 1),
                pw.SizedBox(height: 20),
                pw.Header(level: 1, text: 'Academic Profile'),
                pw.Text('Institution: President University'),
                pw.Text('Major: $major'),
                pw.SizedBox(height: 20),
                pw.Header(level: 1, text: 'Professional Status'),
                pw.Text('Current Status: $activityStatus'),
                if (company != null) pw.Text('Current Organization: $company'),
                pw.SizedBox(height: 40),
                pw.Text('Generated by PresUnivGo AI Assistant', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
