// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1fIfJ7kUwi5yz23LpoHP-q0svbWjL-Us',
    appId: '1:254034416381:web:02d9d76d2ff226d8fce494',
    messagingSenderId: '254034416381',
    projectId: 'puconnect-9e8fb',
    authDomain: 'puconnect-9e8fb.firebaseapp.com',
    storageBucket: 'puconnect-9e8fb.firebasestorage.app',
    measurementId: 'G-70HHZS06CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrdd7gloEk5T1QM_R0jCAceaNBrrO_q34',
    appId: '1:254034416381:android:dbf02d3072aeebe3fce494',
    messagingSenderId: '254034416381',
    projectId: 'puconnect-9e8fb',
    storageBucket: 'puconnect-9e8fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BzfGzl6SseXbrgc4VgiYB8SUw1OG9aA',
    appId: '1:254034416381:ios:65469db0bebfe705fce494',
    messagingSenderId: '254034416381',
    projectId: 'puconnect-9e8fb',
    storageBucket: 'puconnect-9e8fb.firebasestorage.app',
    iosBundleId: 'id.ac.president.presunivgo',
  );
}
